services:
  backend:
    image: abhyuday1212/backend-assignment:latest
    init: true
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
